server:
  port: 8081

logging:
  level:
    root: info
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type:
      jcache
    jcache:
      config:
        classpath:ehcache.xml
  main:
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/fss?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC"
    username: "root"
    password: "!Password404!"
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${keycloak.base.URL}/realms/${keycloak.base.realm}"
          jwk-set-uri: "${keycloak.base.URL}/realms/${keycloak.base.realm}/protocol/openid-connect/certs"
      client:
        registration:
          keycloak:
            client-id: user-rs
            client-secret: pvPxOeuMoW2eJraXIFzqP8A8sMSs8KFw
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope: openid
        provider:
          keycloak:
            token-uri: "${keycloak.base.URL}/realms/${keycloak.base.realm}/protocol/openid-connect/token"

keycloak:
  base:
    URL: "http://localhost:8080"
    realm: "oauth2-realm"
  webclient:
    registrationId: "keycloak"
    url: "${keycloak.base.URL}/admin/realms/${keycloak.base.realm}"

file-storage:
  on-disk:
    path:
#      ${java.io.tmpdir}/javaSaves
      C:\Users\DarkRymit\Desktop\Диплом\data